### PR TITLE
Rename attributes `hash` to `partition_key` and `range` to `sort_key`

### PR DESCRIPTION
**Pull request by Phrohdoh**
## What did you implement:

Renamed attributes `hash` to `partition_key` and `range` to `sort_key`.

See reasoning in #69.

Closes: https://github.com/softprops/dynomite/issues/69

#### How did you verify your change:

```shell
$ cargo test # all non-ignored tests pass
```

```shell
$ rg -t rust -w hash | wc -l
       0

$ rg -t rust -w range | wc -l
       0

$ rg -t rust -w partition_key | wc -l
      10

$ rg -t rust -w sort_key | wc -l     
       4
```

#### What (if anything) would need to be called out in the CHANGELOG for the next release:

This is a breaking change so we should call out the rename and _probably_ bump to `0.6`.

### CODE REVIEW

**Comment by softprops** [comment]
Sorry for the delay. This looks good and lines up better with [the docs](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.CoreComponents.html#HowItWorks.CoreComponents.PrimaryKey).

Since we're making a breaking change, what do think about namespacing the attributes as mentioned [here](https://github.com/softprops/dynomite/issues/69#issuecomment-524629191)?

I'm a fan of `#[dynomite(partition_key)]`

**Comment by Phrohdoh** [comment]
Will do.  This'll take a bit of (IMO needed) refactoring so will take some time.

**Comment by Phrohdoh** [comment]
Done!
Let me know if you'd like the commits squashed, please.

**Comment by softprops** [comment]
Seeing some errors in tracks

```
/home/travis/build/softprops/dynomite/dynomite)
error: proc-macro derive panicked
  --> dynomite/tests/derived.rs:20:10
   |
20 | #[derive(Item, Default, PartialEq, Debug, Clone)]
   |          ^^^^
   |
   = help: message: Can't set more than one `partition_key
```

**Comment by Phrohdoh** [comment]
Oh oops, I forgot to remove the intentionally duplicate `#[dynomite(partition_key)]` attr.
Updated.

**Comment by Phrohdoh** [comment]
The [latest Travis failure](https://travis-ci.org/softprops/dynomite/jobs/582302140) seems to not be caused by this PR but by `rustfmt` missing from the latest nightly channel.

**Comment by softprops** [comment]
This is fine. I see rustfmt is broken on nightly https://rust-lang-nursery.github.io/rust-toolstate/

**Comment by softprops** [comment]
I'll try to get a new release out this week

**Comment by softprops** [comment]
@Phrohdoh thanks again for your work on this I just published 0.6.0 with these changes

**Pull request merged**
