### PR TITLE
Introduce `#[dynomite(skip_serializing_if = "..")]` attribute

### PR DESCRIPTION
**Pull request by Veetaha**
Tested:
- There are no breaking changes 
- The changes are tested in integration tests for both successful and error (trybuild) cases

## What did you implement:

This basically reflects `serde::skip_serializing_if` attribute.
This will be very useful for us to get rid of manual workarounds where we need to store empty binary sets in a db record.

Also had to fix a clippy lint of implementing `Into` trait instead of `From` to let CI pass

#### How did you verify your change:

Ran tests. I've also moved integration tests into a single test binary as per [this article](https://matklad.github.io/2021/02/27/delete-cargo-integration-tests.html)

#### What (if anything) would need to be called out in the CHANGELOG for the next release:

The new feature is specified in changelog in this diff

### CODE REVIEW

**Comment by softprops** [comment]
Happy to merge this when ci is green. Looks like there are still clippy errors

**Comment by Veetaha** [comment]
@softprops, I've fixed the remaining with clippy and rustfmt. They suddenly appeared because we use `stable` rust toolchain on CI and once the toolchain updates, new clippy and rustfmt lints are added, which suddenly makes our CI red.
I suggest we hardcode the version of the toolchain in our CI to make it resistant to rust updates and update the version explicitly. But that's not related to this PR, we can merge it as is.

**Comment by softprops** [comment]
> hardcode the version of the toolchain in our CI to make it resistant to rust updates

That works too. these issues tend to be rare enough that updating pins becomes its own maintenance issue :) Lets try that and see if it fixes the issue the issue so we can move this pull to merge

**Comment by softprops** [comment]
derp. its green now. merging

**Pull request merged**
