### PR TITLE
Improved support for optional attribute values.

### PR DESCRIPTION
**Pull request by elslooo**
## What did you implement:

Closes: #83 

#### How did you verify your change:

1. `cargo build` and `cargo test -- option_`.
2. Integration in separate project is working correctly.

#### What (if anything) would need to be called out in the CHANGELOG for the next release:

This PR fixes an issue with using `None` when sending `PutItem` request to the AWS API.

### CODE REVIEW

**Comment by softprops** [comment]
Nice catch @elslooo. To clarify this change is about supporting unsetting values which may be  nullable in [dynamobd speak](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_AttributeValue.html) correct?

Just so I understand the current behavior, currently passing Option None would have no effect since it previouslt just used the default value which is to not serialize due to the empty valueness of that field with it being empty. Is that correct?

**Comment by elslooo** [comment]
That's correct! Exactly one of the attribute types should be set, but that's not currently the case. While `Some(vec![...])` is `{ B: Some("b64") }`, `None` should be simply `{ NULL: true }`.

Currently, `None::<Vec<_>>` was `{}` (i.e. `AttributeValue::Default`). But the API doesn't accept that:

```
Supplied AttributeValue is empty, must contain exactly one of the supported datatypes
```

With this PR, `None` is simply `{ NULL: true }`, which does get accepted by the API when putting a new item.

---

Additionally, this PR also fixes a similar issue with converting back values retrieved from the API.

Currently, if the API type does not match the rust type, the value is converted into `None::<T>` (even if `T` is an unrelated type). Consequently, that also generalizes to `{ NULL: Some(true) }` (this is probably why the bug wasn't caught). However, I think strict type checking would be better.

With this PR,  e.g. `Option<T>::from_attr(...)` returns an error when trying to convert into a non-related type, except for `NULL` which is accepted regardless of `T`.

The second part is a breaking change if users rely on the somewhat more forgiving behavior that is currently in place.

**Comment by softprops** [comment]
Thanks for explaining. Great find.

**Comment by softprops** [comment]
published your change in an 0.7.0 release. thanks for the work on this one!

**Pull request merged**
