### PR TITLE
Added support for rfc3339 timestamps through the humantime crate and feature

### PR DESCRIPTION
**Pull request by cedric-h**
## What did you implement:
Added a cargo feature to the crate which allows end users to easily serialize `std::time::SystemTime`s into human readable rfc3339 timestamps, by implementing `Attribute` for SystemTime and using `humantime`'s implementation of rfc3339 timestamps internally.

#### How did you verify your change:
Added 2 tests to lib.rs

#### What (if anything) would need to be called out in the CHANGELOG for the next release:
"Added support for rfc3339 timestamps through the `humantime` crate and feature"

### CODE REVIEW

**Comment by zprobst** [comment]
Nice. I just stumbled on this repo and considered adding a similar change. Glad to see that there is interest in this outside of me. Good Stuff!

**Comment by softprops** [comment]
Thanks for the patch. I'm curious why humantime and not a crate chrono, which covers a much broader range of structured time use cases in applications?

Here are the analogs you might be looking for 

https://docs.rs/chrono/0.4.11/chrono/struct.DateTime.html#method.parse_from_rfc3339

https://docs.rs/chrono/0.4.11/chrono/struct.DateTime.html#method.to_rfc3339

There's also built in conversions from system time of your application deals in that.

**Comment by softprops** [comment]
The reason why I ask is that I think humantimes primary target is pretty printing and parsing potentially arbitrary user entered time. 

I understand that it also has rfc3339 support but that feels kind of tacked on. 

I'd rather support time though a crate that specializes in it.

**Comment by cedric-h** [comment]
Absolutely, in retrospect my choice of time crate was rather naive. I'll roll out a commit here in the next hour which replaces `humantime` with `chrono`.

**Comment by cedric-h** [comment]
Sorry that commit took so long, Linux problems :sweat_smile:

**Comment by softprops** [comment]
> Sorry that commit took so long, Linux problems

Not at all. If anything I have to apologize for my slow turn around. I'm a new dad and taking care of a new born so I'm a bit slower to respond recently. I'll try to release a new version tomorrow. I may build on this to support a few other common chrono types.

**Comment by softprops** [comment]
@cedric-h you're changes are now published in 0.8.1!

**Pull request merged**
